### ISSUE TITLE
юзер репорты

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.core#1]
сюда пишем репорты от тех, кто начинает запускать кор, какие мысли посещают, как изменить ридми чтоб следующим кто будет использовать кор было прще его запустить и проще разобратся, особенно тем, кто не состоит в команде. 

Алексей напиши о своем опыте, с какими пробемами столкнулся, как их решил и тп, паша позже примет к сведению

**Comment by caffeinum** [comment]
Когда я запускал, были несоответствия между ридми и кодом в `createSwap <-> createOrder`. Сейчас Паша это уже поправил, но нужно еще обратить на это внимание, чтоб везде было одинаково

**Comment by caffeinum** [comment]
В `new SwapApp()` нужно передавать специальным образом инстансы `bitcoinjs, web3, ipfs, ipfs-pubsub-room`, надо об этом отдельно в ридми написать

**Comment by caffeinum** [comment]
На новом компьютере `ipfs`, а может, `ipfs-pubsub-room`, запускается каждый раз только через полчаса-час. Непонятно, с чем связано. Эта же проблема возникла и у Алексея из аудита.

Зато, когда заработает, то дальше все хорошо. Можно перезапускать приложение, перезагружать комп - все работает.

Вряд ли дело в айпи адресе, потому что из офиса у меня с первого компьютера настроилось, а со второго не сразу.

Возможно, нужно, чтоб наш сервер кидал в эту комнату какое-то сообщение, которое всегда там будет висеть, и если клиент его не находит, то пишет, что не может ничего найти, но **продолжает пытаться**.

@pavelivanov @noxonsu

**Comment by pavelivanov** [comment]
Что значит "кидать сообщение которое там будет висеть" ?

**Comment by caffeinum** [comment]
@pavelivanov а как ты предлагаешь?

**Comment by pavelivanov** [comment]
А чем это поможет? ведь сообщение выполняется сразу. Не уверен что это поддерживает комнату в активном состоянии и вообще может решить описанную выше проблему. Нужно выявить баг точно, чтобы понять как фиксить или дебажить
