### ISSUE TITLE
Если пропустить важное сообщение, то стороны теряют синхронизацию

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.core#100]
В браузере переключился на воллет, пока транза майнилась, в итоге браузер не знает, что она замайнилась

**Comment by caffeinum** [comment]
@noxonsu нет, обновление не помогает, потому что второй чувак уже на другом шаге и не пришлет опять это сообщение

**Comment by caffeinum** [comment]
Надо глубже исследовать, возможно виноват высокий газ в сети

**Comment by nikdementev** [comment]
Как они пропустят, я добавил переотправку если второго участника нет онлайн и плюс у нас подтверждение что сообщение дошло ?

**Comment by caffeinum** [comment]
Сейчас сообщения дублируются, давно такого бага не было, можно закрыть
