### ISSUE TITLE
Сделать функцию refund для EOS

### ISSUE THREAD

**Issue by nikdementev** [swaponline/swap.core#105]
она должна принимать owner and participant  address
refundByOwners(owner, participant)
на данный момент используется swapId следовательно если ты его не знаешь
нельзя больше меняться с конкретным человеком

**Comment by caffeinum** [comment]
@7flash что скажешь?

**Comment by 7flash** [comment]
В одном из предыдущих коммитов это было решено. Теперь функция refund принимает адрес второго участника. Так как между двумя участниками может быть только один активный своп, функция находит активный своп между пользователем и вторым участником, и делает refund транзакцию от пользователя.
https://github.com/swaponline/swap.core/blob/7d657f68b86d093e355aa74329a027267d575488/src/swap.swaps/EosSwap.js#L177
