### ISSUE TITLE
Тесты для core (Insufficient balance)

### ISSUE THREAD

**Issue by momonomonoto** [swaponline/swap.core#11]
Написать тесты для core согласно следующей инструкции:
- `Alice` = `BTC` owner
- `Bob` = `ETH` owner
- `Alice` = order creator
- [ ] Alice creates the order BTC2ETH, but has no funds
- [ ] Alice creates the order ETH2BTC with no ETH (she needs ETH for gas)
- [ ] Bob accepts the order, but has no funds
- [ ] Alice(Bob) passes the stage where balance is checked, but after that sends money away from her account

Лучше начать с тестирования получения текущего баланса.

**Comment by momonomonoto** [comment]
Скинул PR для баланса

**Comment by caffeinum** [comment]
использовать тестовый блокчейн и truffle box - небольшой контейнер для тестирования dApps

**Comment by noxonsu** [comment]
у нас кросчейн, если использовать трюфель, то и для битка что топодобное должно быть., кроме того в проде поведение апа отличается от синтетических тестов, но согласен тесты нужны

**Comment by caffeinum** [comment]
тесты есть теперь в репо swap.truffle
