### ISSUE TITLE
Message 'stop swap', method stopSwap()

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.core#110]
добавить во флоу метод "отменить свап", который будет отправлять сообщение другой стороне, и убивать продолжение обмена

**Comment by nikdementev** [comment]
После создания BTC Script он не нужен, следовательно он нужен только на первых двух шагах
скажи какое видишь применение ?

**Comment by caffeinum** [comment]
он не нужен только после того, как ETH withdraw сделали. До этого момента все обратимо

**Comment by caffeinum** [comment]
@noxonsu это нужно будет сделать, просто пока несрочно, видимо
