### ISSUE TITLE
tether stable price

### ISSUE THREAD

**Issue by 7flash** [swaponline/swap.core#119]
It would be nice to calculate rate of exchange with tether at the moment when participant accepts swap

**Comment by caffeinum** [comment]
Только для тезера или для всех валют?

**Comment by 7flash** [comment]
Только для тезера, потому что его суть в том, чтобы он всегда продавался по фиксированному курсу к доллару, то есть, по такому курсу к другим криптовалютам, который всегда можно рассчитать.

**Comment by caffeinum** [comment]
Я не понял, что значит "рассчитать". Взять курс обмена этой валюты к доллару? или к тезеру? а с какой биржи? 

Речь про обмены SWAP-USDT или BTC-ETH ? Или про все сразу?

**Comment by caffeinum** [comment]
Сейчас это есть на странице /exchange, но только для долларов, а не для USDT.
