### ISSUE TITLE
Если BTC fundScript вернул ошибку, то scriptValues не сохранятся

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.core#121]
https://github.com/swaponline/swap.core/blob/5d420783790f9587d58c0206ae465b716db57029/src/swap.flows/BTC2ETH.js#L146

почему это плохо? иногда нода возвращает ошибку, хотя транзакцию приняла и замайнит. 

![image](https://user-images.githubusercontent.com/1909384/45790302-d03e7e80-bc8c-11e8-99a3-327f7c3b5320.png)

**Comment by noxonsu** [comment]
стоит при повторной отправке транзы пытатся найти ее в есплорере (и если есть то выдавать саксес?)

**Comment by caffeinum** [comment]
Нет, обновление не поможет. Нужно сохранять scriptValues сразу после генерации

**Comment by caffeinum** [comment]
Это сделано в BTC2ETHTOKEN, нужно то же самое сделать в BTC2ETH. @shendel
