### ISSUE TITLE
добавить актуальные исходники контрактов в core для эфира

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.core#122]
сейчас исходников контрактов пока нигде нет, нужно чтоб они были внутри кора, например в папке smartcontracts (посоветуйся с Игорем который делает для еоса тоже)

**Comment by caffeinum** [comment]
swaponline/swap.truffle

**Comment by noxonsu** [comment]
ссылку вставь в комент там где адрес коонтракта в коре изакрывай

**Comment by nikdementev** [comment]
адреса контрактов только в примере указываются
