### ISSUE TITLE
подключить litecoin

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.core#126]
в core подключить блокчейн лайткоина, для начала научится получать баланс (делать utxo транзакции)

**Comment by nikdementev** [comment]
как связан core, и вывод на балансы в реакте ? @noxonsu

**Comment by noxonsu** [comment]
переписал ишью, хотел разбить на две части, что бы подключить свапы лайткоина нужно начать с того, что разобратся с тем как работают utxo транзакции, после чего перейти к созданию смарт контрактов на лайткоине

**Comment by caffeinum** [comment]
@nikdementev @sdwas я думаю можно обойтись без отдельной либы, так же как с BCH, что либа биткоина подойдет

**Comment by noxonsu** [comment]
согласен, стоит проверить этот вариант. тем более есть litcoinjs построенный на основе bitcoinjs
