### ISSUE TITLE
Вызывать несколько раз подряд методы у new Swap()

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.core#13]
Так как он хранит состояние в localStorage, он восстановит уже начатый своп, но если повторить заново все действия, он будет сходить с ума (например, будет ругаться на то, что транзакция уже известна)

Пока что не исследовал, но в [caffeinum/swap.core](github.com/caffeinum/swap.core) при вызове `/swaps/:id/go` несколько раз подряд состояние ломается. Возможно, связано с #7

**Comment by pavelivanov** [comment]
Не совсем понял о чем речь, но пришли к решению что зачищать своп / ордера должен создатель апп, в коре этого не будет (пс можно добавить опцию в конфигурацию, но опять же пока нет)

**Comment by caffeinum** [comment]
это исправили добавлением проверок на публичных методах
