### ISSUE TITLE
избавиться от ненужных данных в swap

### ISSUE THREAD

**Issue by nikdementev** [swaponline/swap.core#134]
![image](https://user-images.githubusercontent.com/17093843/46381788-74262200-c6b0-11e8-84cb-099b4fcf8210.png)
В каждом свапе у нас есть информация о всех кошельках человека, а именно eth, btc, ltc, eos,
хоть для процесса обмена нужно только два и всегда нужен кошелек eth
надо продумать этот момент

**Comment by noxonsu** [comment]
пока не мешает, продумаем если будет реально мешать
