### ISSUE TITLE
Неправильный порядок импорта модулей в babel версии для NodeJS

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.core#14]
![image](https://user-images.githubusercontent.com/1909384/41206829-470b5408-6d13-11e8-856d-4fa42c47d889.png)
```bash
TypeError: EthSwap is not a constructor
     at Object.<anonymous> (/Users/caffeinum/Web/swap.core/server/wallet/swaps.js:17:3)
```

```javascript
const { EthSwap, EthTokenSwap, BtcSwap } = require('../swap-core/swap.swaps')
...

new EthSwap({...})
```

где swap-core это папка с модулями, собранная с помощью webpack и команды

```bash
NODE_ENV=development ../node_modules/webpack-cli/bin/cli.js --config webpack.config.babel.js
```

а webpack.config.babel.js совпадает с файлом https://github.com/swaponline/swap.core/blob/new/examples/react/webpack.config.babel.js

**Comment by caffeinum** [comment]
```bash
Error: SwapAuth._initService(): TypeError: Cannot read property 'web3' of undefined
          at /Users/caffeinum/Web/swap.core/swap-core/services/swap.auth/SwapAuth.js:69:17
```

**Comment by caffeinum** [comment]
![image](https://user-images.githubusercontent.com/1909384/41207200-12338046-6d1a-11e8-8113-26e500e9a083.png)

**Comment by caffeinum** [comment]
https://github.com/caffeinum/swap.core/commit/f938aff89b1f8e167d76cbf4ead5a31ec9bd35d7

пока что вернул импорты обратно, надеюсь, это заработает, как нужно

**Comment by pavelivanov** [comment]
Ошибки никакой нет. Просто есть такая замечательная штука - https://www.npmjs.com/package/app-module-path

**Comment by caffeinum** [comment]
# Ошибка

![image](https://user-images.githubusercontent.com/1909384/41511126-7dd6d2c6-7279-11e8-8b95-c417ccc84a45.png)

# Как воспроизвести

```bash
npx babel ./src --out-dir ./lib
npm install --save node-localstorage ipfs ipfs-pubsub-room web3 bitcoinjs-lib
node test.js
```

```javascript
file test.js:

require('app-module-path').addPath(__dirname + '/lib')

const Ipfs = require('ipfs')
const IpfsRoom = require('ipfs-pubsub-room')

const LocalStorage = require('node-localstorage').LocalStorage
const storage = new LocalStorage('./storage/test')

const bitcoin = require('bitcoinjs-lib')
const Web3 = require('web3')

const web3 = new Web3(new Web3.providers.HttpProvider('https://rinkeby.infura.io/JCnK5ifEPH9qcQkX0Ahl'))

const SwapAuth = require('swap.auth').default
const SwapRoom = require('swap.room').default
const SwapOrders = require('swap.orders').default

const SwapApp = require('swap.app').default

SwapApp.setup({
  network: 'testnet',
  env: {
    Ipfs, IpfsRoom,
    storage,
    bitcoin,
    web3,
  },
  services: [
    new SwapAuth({
      eth: null,
      btc: null,
    }),
    new SwapRoom({
      EXPERIMENTAL: {
        pubsub: true,
      },
      config: {
        Addresses: {
          Swarm: [
            '/dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star',
          ],
        },
      },
    }),
    new SwapOrders(),
  ],
  swaps: [],
})
```

# Еще скриншоты
![image](https://user-images.githubusercontent.com/1909384/41511148-e461bf88-7279-11e8-9ab8-8b5e35a20bf7.png)

```this.env не пустой```

![image](https://user-images.githubusercontent.com/1909384/41511153-084addc6-727a-11e8-868d-73ca599db01b.png)

но внутри `eth.js` почему-то `SwapApp.env` пустой

![image](https://user-images.githubusercontent.com/1909384/41511161-3ddfb524-727a-11e8-877e-956cf49c0bea.png)

и внутри `SwapAuth.js`


И вот на этой строчке падает ошибка:

![image](https://user-images.githubusercontent.com/1909384/41511174-722d9486-727a-11e8-905f-fd5ef8e7e0bd.png)

![image](https://user-images.githubusercontent.com/1909384/41511176-7d4c079e-727a-11e8-87f5-2db02b8fd803.png)

**Comment by caffeinum** [comment]
Про app-module-path нужно добавить в рид-ми тогда

**Comment by pavelivanov** [comment]
он нужен только для дева тебе) кто как резолвит пути у себя в апп из папки src - дело разраба. В прод версии (в виде npm пакета) app-module-path не нужен
