### ISSUE TITLE
flow: атака с подменой хэша на эфире

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.core#142]
Мы сейчас извлекаем секрет прямо из сырой транзакции. Это значит что секрет можно забрать, даже если транзакция не сработает.

Решение: перед публикацией транзакции проверять, что хэш в контракте совпадает с нужным

![image](https://user-images.githubusercontent.com/1909384/46619932-0b193100-cb2c-11e8-8e33-f193fedffc9c.png)

**Comment by noxonsu** [comment]
почему холд?
