### ISSUE TITLE
Получать секрет из контракта

### ISSUE THREAD

**Issue by 7flash** [swaponline/swap.core#155]
На данный момент, владелец биткоина может забрать эфир/эос из контракта и не сообщить о том, что опубликовал секрет. Владелец эфира/эоса рискует узнать об этом только после того, как время для получения биткоина истечет.

**Comment by 7flash** [comment]
Решение: добавить проверку в интервале, что секрет опубликован и выводить биткоин даже если, участник не сообщил транзакцию

**Comment by caffeinum** [comment]
В эфире сейчас такая же проблема (в USDT2ETHTOKEN ее кстати нет, можно взять код оттуда)

**Comment by caffeinum** [comment]
Тоже можно закрывать, и в эфире, и в токенах это уже есть. Спасибо @a37h
