### ISSUE TITLE
Watchtower для withdraw на биткоине

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.core#162]
В начале свопа подписывать и refund, и withdraw, и хранить на сервере.

Если что-то пойдет не так, сервер задеплоит соответствующую транзакцию

**Comment by nikdementev** [comment]
у нас нет сервера, почему это не делать на фронте при какой либо ошибке
не подписывать и не отправлять ?

**Comment by noxonsu** [comment]
потому что клиент закрывает страницу если что то пошло не так, долго ждем второго чела например, а 180 минут ждать долго. идея здравая, надо делать

**Comment by nikdementev** [comment]
я бы не доверял сервису который делает так что отправляет за меня мои транзакции без моего разрешения) это уже обычная биржа получается)

**Comment by caffeinum** [comment]
@nikdementev в смысле без разрешения? сервис не может никакую транзакцию отправить, кроме той, что ты сам ему пошлешь

**Comment by nikdementev** [comment]
я ему отправил она не дошла, еще что то потом я захотел вернуть бабки, а старая транза дошла и все тп) это имел ввиду

**Comment by caffeinum** [comment]
наверное, это будет в рамках swap.explorer и платной подписки

**Comment by noxonsu** [comment]
пока не нужно, хорошо работает автовозврат при заходе в историю
