### ISSUE TITLE
ошибка если рефанд пытатся сделать несоклько раз

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.core#163]
если я нажал трай рефанд, а потом через некоторое время еще раз, то в интерфейсе ничего не происходит, а в консоли пишет ошибку типа уже потрачены биткоины. нужно корректно отрабатывать этот момент

**Comment by nikdementev** [comment]
тогда почему issue тут а не в интерфейсе ?

**Comment by noxonsu** [comment]
https://github.com/swaponline/swap.react/issues/762
