### ISSUE TITLE
3.1.1. Отсутствие взаимной аутентификации участников 

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.core#17]
Критичность: средняя Вероятность эксплуатации: средняя Итоговый риск: средний 
Описание: При обмене сообщениями участники никак не аутентифицируют друг друга. 
Риск: Злоумышленник может генерировать поддельные ордеры от чужих адресов и снижать тем самым репутацию участников и платформы. 
Уязвимый ресурс:  Swap-core Технические детали: Поскольку для того, чтобы проводить обмен, необходимо обладать секретным ключом, то аутентификация все же присутствует, но происходит на более позднем этапе. 
Рекомендации:  Подписывать сообщения, которыми обмениваются участники. В качестве приватных ключей предлагается использование тех же, чьи адреса участвуют в процессе обмена, и которым в последствие присуждается рейтинг. Более развёрнуто см. в п. 6.2. Статус:  Не ответили

**Comment by pavelivanov** [comment]
fixed
