### ISSUE TITLE
BTC2ETHTOKEN: Skips step 3, when insufficient funds.

### ISSUE THREAD

**Issue by sdwas** [swaponline/swap.core#173]
BTC2ETHTOKEN VS BTC2ETH

![screenshot_20181114_184406](https://user-images.githubusercontent.com/43396375/48470488-4ef30a80-e83d-11e8-8513-b07834fd824c.png)

**Comment by caffeinum** [comment]
не, погоди, это так и нужно

**Comment by caffeinum** [comment]
да, так и задумано
