### ISSUE TITLE
simple/example/bot.js "emmiter.on is not a functon" при старте свапа

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.core#182]
![](https://airdb.wpmix.net/putty_sizebox_2018-11-21_04-58-421b73246d-b620-4ec0-9ebe-da2f0358b698.png)

**Comment by caffeinum** [comment]
Сейчас работает:

![image](https://user-images.githubusercontent.com/1909384/50919219-44c34600-1453-11e9-871b-2b04a5d3f3d6.png)




![image](https://user-images.githubusercontent.com/1909384/50919249-5573bc00-1453-11e9-9b16-849f9413bf0a.png)
![image](https://user-images.githubusercontent.com/1909384/50919257-5c9aca00-1453-11e9-9b4c-fb11073f4e0c.png)
