### ISSUE TITLE
3.2.2. Хранение приватных ключей в localstorage 

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.core#19]
Описание: Приватные ключи участников хранятся в браузере. 
Риск: При наличии у атакующего возможности внедрения Javascript-кода на страницу пользователя он сможет без труда компрометировать приватные ключи. 
Уязвимый проект:  swap-core Технические детали: Приватные ключи (Bitcoin и Ethereum) участников хранятся в браузере с использованием localstorage, что значительно облегчает их кражу в случае XSS. 
Рекомендации:  Позволить пользователю использовать кошелек Metamask для Ethereum.  Рассмотреть вариант создания/использования аналога Metamask для Bitcoin.  Шифровать приватные ключи на пароле пользователя, которые необходимо запрашивать при совершении транзакций (менее приоритетный вариант). Статус:  Не ответили

**Comment by noxonsu** [comment]
запланировано (keychain)

**Comment by caffeinum** [comment]
https://github.com/Lamden/clove-sign-plugin

**Comment by pavelivanov** [comment]
@noxonsu в апп нужно подключать MetaMask

**Comment by vladiuz1** [comment]
> У меня есть прототип HD wallet для одного seed для биткоина и эфира
https://iancoleman.io/bip39/#english
