### ISSUE TITLE
3.2.3. Использование устаревших библиотек, имеющих уязвимости 

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.core#20]
Описание: В проекте используются библиотеки, имеющие публично известные уязвимости. 
Риск: Атакующий может использовать уязвимости в целях компрометации Системы. 
Уязвимый проект:  swap-core Технические детали: Анализ зависимостей проекта показал, что используется устаревшая версия пакета randomatic. Описание уязвимости (слабый генератор случайных чисел). 
Рекомендации:  Принудительно указать в package.json последнюю версию пакета. Статус:  Не ответили

**Comment by noxonsu** [comment]
https://nodesecurity.io/advisories/157

**Comment by pavelivanov** [comment]
В коре никак не используется. Является зависимостью либы fill-range, которая является зависимостью: webpack / ava / watchpack
