### ISSUE TITLE
6.2.2. Управление ордерами 

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.core#21]
a. Стоит добавить в объект ордера метку времени, означающую «до какого времени я хочу начать обмен». Таким образом достигается защита от дубликатов (поскольку peed id выбирается самим пиром, то его можно подделать), а также от «зависших» пиров. Также это поможет избавляться от неактуальных ордеров в автоматическом режиме. b. Стоит дать пользователю возможность удалять свои ордеры (сделанные по ошибке или более не актуальные). 
Статус:  А. Павел: «Защита от дубликатов таким образом никак не достигается, такую защиту можно достигнуть проверкой дубликатов при создании ордера (по введенным данным currency / amount) и оповещать юзеров.»  
Алексей: «дубликат имеется ввиду следующий. Я просто беру старый заказ кого-то чужого и отправляю. Если в нем будет метка времени, то можно будет посмотреть, что если уже есть такой ордер в стакане или по самому времени видно что он из прошлого (час назад сделан например)» 
B. Павел: «такая возможность есть». Значит проблемы нет.

**Comment by pavelivanov** [comment]
1) Кол-во ордеров в стакане от одного юзера определяется нуждами самого проекта
2) Есть функционал удаления ордеров - так что любой юзер может это сделать в любое время

СМ коммит - добавлена проверка что тот кто создает ордер (посылает его в рум) является его овнером (по пиру отсылающего)
