### ISSUE TITLE
6.2.4. Генерация bitcoin script 

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.core#22]
BTC owner может убедиться, что на предоставленном ETH owner Bitcoin адресе есть средства для того, чтобы на последнем этапе забрать средства. ETH owner должен побайтово валидировать скрипт, предоставленный BTC owner.  
   

 
a. Убедиться, что скрипт соответствует нужной структуре:  1. ETH owner может забрать биткоин, предоставив секрет. 2. BTC owner может забрать биткоин только по истечении оговоренного на первом этапе времени. b. В скрипте нет лишних частей, которые могут повлиять на его логику. c. Установлены верные дата и количество биткоинов (по установленному курсу из ордера). При этом: 1. Дата должна ровняться сумме: «дата, установленная при вызове sign» плюс «оговоренное время на сделку». 2. Так же текущая дата не должна быть позднее чем дата, установленная при вызове sign, более чем на пару минут. Другими словами, надо быть уверенным, что есть достаточно времени для того, чтобы закончить сделку. Все эти проверки проще делать через генерацию этот скрипта средствами ETH owner и последующее побайтовое сравнение. 
Статус: Павел: «Не понял посыл текста. В данный момент реализована выдача данных по скрипту противоположной стороне чтобы она могла проверить его + скрипт отдается в изначальном виде со всеми открытыми данными, что позволяет проверить все досканально, по желанию.» Алексей: «Обычные пользователи не будут ничего проверять, да и продвинутые тоже не будут байты ковырять. Тут речь только о том чтобы реализовать все проверки в автоматическом режиме на стороне ETH owner.» Итог: друг друга не поняли немного. Нужен дальнейший диалог.

**Comment by pavelivanov** [comment]
Решено проверять 3 параметра: lockTime, recipientPublicKey, btc script balance

**Comment by noxonsu** [comment]
так как скрипт не приходит целиком, приходят только переменные, из которых по готовому шаблону генерится скрипт на стороне боба. далее просто мы сверяем что полученный p2sh адрес совпадает. Получается сам скрипт зашит в код его нельзя поменять. 

>  надо быть уверенным, что есть достаточно времени для того, чтобы закончить сделку.
мы проверяем что локтайм больше чем будет встречный когда будет морозится эфир от боба. пока что прошит 1 час вперед для бтс и сделаем, чтоб при встречном свапе лочилось на таймаут меньший чем этот lockTime и тогда условие выполняется

> Так же текущая дата не должна быть позднее чем дата, установленная при вызове sign, более чем на пару минут. 

дата в sign никак не влияет на безопасность. ну мы можем чисто формально добавить проверку, чтоб sign был меньше locktime только это ничего не даст. дата в сайне просто на всякий случай добавлена
