### ISSUE TITLE
6.2.5. Вызов createSwap 

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.core#23]
ETC owner ожидает, пока bitcoin-скрипт будет отправлен в сеть, и после этого должен убедиться, что это именно тот скрипт, что прислан на предыдущем этапе. В случае успеха он вызывает функцию createSwap и убеждается в успешности транзакции. BTC owner ожидает пополнение сделки на оговоренную сумму Ether. Уведомление об этом он получает от ETC owner и прослушивая события контракта (информация в событии в приоритете). Так же возможна дополнительная проверка по расписанию через вызов getInfo. 
Статус: Павел: «добавлена передача урла транзакции» #d45b86087918e9bdf54d342b36e72eda525577da Алексей: Хотел бы увидеть код который делает проверки используя этот урл. Итог: друг друга не поняли немного. Нужен дальнейший диалог.

**Comment by pavelivanov** [comment]
swap.truffle: e92d6f8245c2fbe52ab8508c3ee8d2268eb7a260
