### ISSUE TITLE
Swap btc2ethToken не проходит до конца

### ISSUE THREAD

**Issue by sdwas** [swaponline/swap.core#237]
btc2ethToken

balanceCheckResult
 
![screenshot_20190119_024127](https://user-images.githubusercontent.com/43396375/51400776-f588be00-1b94-11e9-8e98-48d29050dd60.png)
![screenshot_20190119_024256](https://user-images.githubusercontent.com/43396375/51400792-ff122600-1b94-11e9-86cf-f4ee6a86ed5a.png)
![screenshot_20190119_024336](https://user-images.githubusercontent.com/43396375/51400793-ffaabc80-1b94-11e9-8049-af33995a4666.png)

![screenshot_20190119_021530](https://user-images.githubusercontent.com/43396375/51399115-e6077600-1b90-11e9-89ba-fca2cf780f5a.png)

**Comment by caffeinum** [comment]
Надо протестить, ПР смержили

**Comment by caffeinum** [comment]
![image](https://user-images.githubusercontent.com/1909384/51420070-4eaa1f00-1ba0-11e9-8daa-60c2dde1d3de.png)
