### ISSUE TITLE
Цикличность withdraw eth / ethToken для всех flow

### ISSUE THREAD

**Issue by sdwas** [swaponline/swap.core#246]
Добавить ключ ошибки ethWithdrawError, чтобы в клиенте предлагать пополнить баланс эфира на комиссию.
Добавить цикличность на шаг 4-5 для всех покупателей эфира / токена

**Comment by caffeinum** [comment]
Мы сейчас вроде бы просто запрещаем начинать своп?

**Comment by sdwas** [comment]
Нет, своп можно начать без баланса.
