### ISSUE TITLE
EthTokenSwap: secure withdraw without fee flow

### ISSUE THREAD

**Issue by shendel** [swaponline/swap.core#248]
Сделать абстрактно withdraw, withdrawNoMoney, withdrawOther - в зависимости от вызванной функции (withdraw или withdrawNoMoney) вызывать withdrawOther с нужными параметрами

**Comment by caffeinum** [comment]
Александр Ноксон, [23.01.19 17:43]
"С refund интересно .... очень.... как вариант - выровнять SafeTime, Из-за чего такой разброс между битком и эфиром (токенами) в два часа?"

суть в том, что если локтайм будет одинаковый, то тот кто биток морозит может подождать 2:59 часа, залочить биток, потом бот залочит эфир, а первый выведет и получит все деньги , и сделает сразу рефанд

Александр Ноксон, [23.01.19 17:44]
мы одновременно с запросом "заверши за меня" ждем минуту и показываем юзеру чтоб пополнил ETH

Лēшå Быхун, [23.01.19 17:45]
> У функций, котором нужно фи, есть опционально параметр calcFee, если его указать (true), то транзакция будет выполнена на ВМ и функция вернет кол-во эфира для фи

Может, это лучше вынести в абстракцию?

Alexander Shestopalov, [23.01.19 17:49]
withdraw (на основе msg.sender) может выполнить только покупатель

Alexander Shestopalov, [23.01.19 17:49]
withdrawNoMoney( на основе msg.sender) только продавец

Alexander Shestopalov, [23.01.19 17:49]
withdrawOther - кто угодно

Лēшå Быхун, [23.01.19 17:50]
почему вместо withdrawNoMoney продавец не может вызывать withdrawOther?

Alexander Shestopalov, [23.01.19 17:51]
предлагаешь оставить только withdrawOther?

Лēшå Быхун, [23.01.19 17:51]
ну по сути только он и нужен

Александр Ноксон, [23.01.19 17:55]
@diademnetwork предложил  ""В качестве варианта решения, предлагаю добавить в контракт дополнительную награду для того, кто вызывает withdrawOther. Таким образом, у сторонних кошельков будет мотивация вызывать этот метод как только это стало возможным. При рассчете суммы награды нужно учесть, что эта функция и так возвращает д

Pavel Khavilov, [23.01.19 18:22]
как делаем? 
1 вариант - появляется надпись о том, что нехватает на фи, ниже кнопка - скопировать адрес, рядом с ней кнопка отправить запрос 
2 вариант появляется текст с инфой о том, что не хватает с адресом и тд и тп. если в течении N минут не пополнен баланс выслать запрос второму юзеру?

Александр Ноксон, [23.01.19 18:28]
просто тупо пишем "запрашиваем вывод с контракта и тихо запрашиваем вторую сторону

Лēшå Быхун, [23.01.19 18:29]
[In reply to Александр Ноксон]
это плохо, потому что секрет опубликуется

Лēшå Быхун, [23.01.19 18:30]
если ты сразу после этого уйдешь в офлайн, то все кранты

Лēшå Быхун, [23.01.19 18:30]
а в другом случае, ты явно узнаешь, что делаешь сложное рискованное действие

Александр Ноксон, [23.01.19 18:33]
[In reply to Лēшå Быхун]
да, это все в новом ишью сделаем

Александр Ноксон, [23.01.19 18:34]
[In reply to Лēшå Быхун]
ну там же написано "запрашиваем вывод с контракта" и нафига мне в офлайн уходить?

Александр Ноксон, [23.01.19 18:34]
когда транзу выполняешь ты же не уходишь (а секрет опубликован)

Лēшå Быхун, [23.01.19 18:36]
[In reply to Александр Ноксон]
в смысле интернет пропал

Лēшå Быхун, [23.01.19 18:36]
между моментом, когда ты отправил секрет второму чуваку

Лēшå Быхун, [23.01.19 18:36]
и до того ,как ты успел придумать, кого попросить запостить транзу

Александр Ноксон, [23.01.19 18:37]
[In reply to Лēшå Быхун]
предлагаю переместить это обсуждение в v2 будет еще один пул где все учтем

**Comment by noxonsu** [comment]
приняли в кор давно
