### ISSUE TITLE
XXX2BTC: ошибка при withdraw btc

### ISSUE THREAD

**Issue by sdwas** [swaponline/swap.core#250]
Своп останавливается на предпослднем шаге, но withdraw проходит успешно.

![screenshot_20190125_003842](https://user-images.githubusercontent.com/43396375/51685277-b5fd1e80-2039-11e9-85a0-1dd4bb9da4e5.png)

**Comment by caffeinum** [comment]
Это потому что он забрал секрет из смарт-контракта и (видимо) попробовал опять снять бабки с биткоина, но он их уже забрал

В пулле #266 я сделал, чтоб прекращал попытки, когда нашел одним способом, но этот баг там НЕ решен.

С другой стороны, это не баг, это ворнинг о том, что дважды пытается выйти с одного и того же шага, но это норм, иначе никак

**Comment by caffeinum** [comment]
Как это надежно воспроизвести?

**Comment by sdwas** [comment]
100% при свопе eth2btc когда у покупателя эфира нет btc. В завершенини свопа у продавца будет ошибка эта

**Comment by caffeinum** [comment]
![image](https://user-images.githubusercontent.com/1909384/52792291-10f3c580-307c-11e9-87b1-7c46033fb14e.png)
подтверждаю

https://rinkeby.etherscan.io/tx/0x580eb0da8410ee64b5894fe1ccdcd8feb8eb6e06b7eed4c21aff6212fa9853f1

https://test-insight.swap.online/insight/tx/5793483078cee03607a5f2202cabb55ab32ce7fd7aa0e9d833e9895ca0375e54

https://test-insight.swap.online/insight/address/2MuVomMUu3fv2fagGYdtnpWX9bcUMp8m3Fq


```json

Developer information
{
    "step": 7,
    "signTransactionHash": null,
    "isSignFetching": true,
    "isMeSigned": true,
    "secretHash": "2e4f3d98cac264acfa90f0ce4ca66a03c0c539ef",
    "btcScriptValues": {
        "secretHash": "2e4f3d98cac264acfa90f0ce4ca66a03c0c539ef",
        "ownerPublicKey": "029047e1058117783bc58268baaa9b47c5373265f2adc0d3692fe6c5eeef7a8882",
        "recipientPublicKey": "037bb0682dbbc6411e7027a41fa98c9935bc264618da50373a4117bf6b736dc80c",
        "lockTime": 1550156589
    },
    "btcScriptVerified": true,
    "isBalanceFetching": false,
    "isBalanceEnough": true,
    "balance": 1,
    "btcScriptCreatingTransactionHash": "5793483078cee03607a5f2202cabb55ab32ce7fd7aa0e9d833e9895ca0375e54",
    "ethSwapCreationTransactionHash": "0x580eb0da8410ee64b5894fe1ccdcd8feb8eb6e06b7eed4c21aff6212fa9853f1",
    "canCreateEthTransaction": true,
    "isEthContractFunded": true,
    "secret": "0x0d3111eed176855959c4fc455bd202cb7e78e82caec34ceba7a4cee081d527e4",
    "isEthWithdrawn": true,
    "isBtcWithdrawn": false,
    "refundTransactionHash": null,
    "isRefunded": false,
    "isFinished": false,
    "isSwapExist": false
}
```

**Comment by caffeinum** [comment]
https://rinkeby.etherscan.io/tx/0xe808f2dadc48908ba3a11e87171d915d39f834bae89859795edbc585f37b81a8

при этом withdraw произошел
