### ISSUE TITLE
Сумма при создании eth контракта отличается от суммы в ордере

### ISSUE THREAD

**Issue by sdwas** [swaponline/swap.core#288]
![screenshot_20190212_200918](https://user-images.githubusercontent.com/43396375/52636359-1932f000-2f18-11e9-9add-dd7438ed8167.png)
![screenshot_20190212_203657](https://user-images.githubusercontent.com/43396375/52636360-1932f000-2f18-11e9-95c6-9d66af77f3e9.png)

**Comment by caffeinum** [comment]
swap.react#1500
