### ISSUE TITLE
ETH2BTC: Остановка на 2м шаге eth2btc

### ISSUE THREAD

**Issue by sdwas** [swaponline/swap.core#289]
Если во время свопа eth2btc у buyer нет битка, и seller решит перейти со страницы свопа на любую другую (например кошелек), то по возвращению он зависнит на 2м шаге, даже когда buyer уже пополнит баланс скрипта.

Решается перезагрузкой страницы.

![screenshot_20190212_173050](https://user-images.githubusercontent.com/43396375/52636514-8fcfed80-2f18-11e9-8d33-58db67f959fe.png)

**Comment by caffeinum** [comment]
там вроде для этого request sign
