### ISSUE TITLE
ETH balance check error: Expected value: 26655825610604432, got: 26655825610604430

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.core#315]
покупаю эфир за биткоин на этапе забора средств не прошли проверку баланса, видимо опять проблема с округлением

ошибка в последнем знаке
![](https://screenshots.wpmix.net/chrome_2019-02-26_04-23-039146bb39-13c1-4032-afaf-a673c9d11828.png)

**Comment by caffeinum** [comment]
![image](https://user-images.githubusercontent.com/1909384/53412711-1f76a100-39db-11e9-80a1-c463fdec0a79.png)

разница в 20 вей

**Comment by noxonsu** [comment]
может это старый бот

**Comment by caffeinum** [comment]
упс, наверное да, его давно не обновляли
