### ISSUE TITLE
SIP1: Экспортить из Flow список методов, которые нужно вызывать вручную

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.core#5]
# Swap Improvement Proposal 1:

Сейчас не очень понятно без примеров кода, как использовать классы BTC2ETH, ETH2BTC, которые субклассы Flow.

В issue#4 есть пример, как немного упростить работу с этим. Например, для тех шагов, где требуется ручное вмешательство, можно экспортить набор:

```javascript
{
    needsSign: enterStep(1),
    needsVerifyBtcScript: enterStep(3)
}
```

```javascript
await flow.needsSign
flow.sign()

await flow.needsVerifyBtcScript
const script = flow.getBtcScript()
console.log('please verify script', script)
await readline() == 'y'
flow.verifyBtcScript()
```

**Comment by noxonsu** [comment]
все импрувмент пропозалы должны быть приведены к виду. 

1. проблема и мотивация
2. варианты решения  (не обязательно)
3. почему именно этот вариант предлагается выбрать
4. пример реализации
5. что получаем по итогу

**Comment by caffeinum** [comment]
Ответ такой: все публичные методы нужно вызывать. Пока что закрываем
