### ISSUE TITLE
Меняются местами buy и sell

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.core#6]
Создавался ордер с 0.007 BTC, а пришел ордер на 7 BTC

![image](https://user-images.githubusercontent.com/1909384/41043659-10e2fa5c-69ad-11e8-8d74-9f5363ddd16f.png)
![image](https://user-images.githubusercontent.com/1909384/41043673-1663ed1a-69ad-11e8-98f5-45f49770e47b.png)

**Comment by nikdementev** [comment]
[У меня тоже самое](https://imgur.com/a/Xbu0Dtx)

**Comment by noxonsu** [comment]
кто котрыл тот и закрывает
