### ISSUE TITLE
не давать стартовать своп если < 0.001 BTC

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.core#65]

**Comment by noxonsu** [comment]
https://github.com/swaponline/swap.react/issues/171#issuecomment-409075606 короче сделаем минимулку для обмена 20 баксов это 0.0025

**Comment by caffeinum** [comment]
запрещать создание ордера или обмен?

**Comment by noxonsu** [comment]
я думаю создание ордера, причем тут актуальные суммы для биткоини и других блокчейнов нужно указывать отдельно. актуальные значение для бтс и етх уточни у никиты (помойму 0.05 для эфира для биткоина хз сколько)

**Comment by caffeinum** [comment]
тут некуда вставить этот код, нужно перенести логику работы с валютами внутрь кора, и как-то немного поменять логику

![image](https://user-images.githubusercontent.com/1909384/44041594-d101ef42-9f26-11e8-9631-425d70f9e4a3.png)

**Comment by caffeinum** [comment]
давай до версии два отложим. В реакте уже есть лимит

**Comment by caffeinum** [comment]
в реакте есть лимит, в коре неправильно его форсить
