### ISSUE TITLE
сделать возможность ввести секрет вручную на этих шагах

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.core#70]
http://joxi.ru/5mdvD3Mck05yRA

**Comment by noxonsu** [comment]
вообще это больше вопрос как клиенту дать больше возможностей завершить свап если автоматом что то не так, например если секрет передается в меседжере

**Comment by caffeinum** [comment]
секрет не передается через месседжинг, на самом деле у нас своп можно провести совсем без айпифс (только адрес скрипта нужно знать) Всю важную информацию чувак получает из смарт-контрактов
