### ISSUE TITLE
проверить ветку new на работоспособность

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.core#8]
https://github.com/swaponline/swap.core/tree/new запустить ветку. совершить обмен. проверить 

* [x] - создание ордеров
* [x] - выполнение свапа

написать тест или просто эмулировать какой то сбой, например один из учатсников просто вышел на первом или втором шаге. 

дописать соответсвующий код который будет правильно обрабатывать эту ситуацию (например выдавать сообщение юзеру о том что произошел таймаут)

**Comment by nikdementev** [comment]
![image](https://user-images.githubusercontent.com/17093843/41274947-a4ea30ee-6e62-11e8-837b-d19cc8ec3c0d.png)
Все деньги переводятся, но вот такая ошибка
