### ISSUE TITLE
атака с маленьким mining fee

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.core#80]
возможна ситуация, когда алиса лочит биток (перевод с utxo 1) но с маленьким mining fee, боб не проверяет это и лочит кефир, алиса забирает кефир и одновременно  еще раз тратит utxo1 (ту с которой пополнен сркипт) уже на себя но с большим майнинг фи и в итоге оказывается и с биткоином и с эфиром. 

по протоколу такая атака нивелируется рейтингом, либо придется ждать хотя бы 1 подтверждения в случае с большими суммами, но есть простой хак, тупо в коре проверять что майнинг фи установлен высокий и транза замайнится с большой вероятностью.

**Comment by caffeinum** [comment]
> в коре проверять что майнинг фи установлен высокий и транза замайнится с большой вероятностью.

Есть сервис у blockcypher, который делает то же самое, плюс машинное обучение. Можно использовать их апи

**Comment by caffeinum** [comment]
https://www.blockcypher.com/dev/bitcoin/#confidence-factor

**Comment by caffeinum** [comment]
во флоу ETH2BTC.js, нужно в проверке скрипта еще и проверять размер комиссии, а также, что думает блокчифер об этой транзакции

**Comment by caffeinum** [comment]
https://www.blockcypher.com/dev/bitcoin/#tx

**Comment by caffeinum** [comment]
ну это вроде бы newbie

**Comment by caffeinum** [comment]
вот эту штуку лучше проверять в клиентском коде, наверное

https://www.blockcypher.com/dev/bitcoin/#tx

**Comment by noxonsu** [comment]
короче проверить тупо, что он такой как мы задумали и не изменен и все. без блокчиперов пока

**Comment by caffeinum** [comment]
Это актуально, у меня сегодня транзакция создания скрипта замайнилась, только когда уже время рефанда подошло. Нужно не только проверять, что комиссия достаточная, но и изначально ставить комиссию по загруженности сети. https://bitcoinfees.earn.com <- у них есть API для этого.
