### ISSUE TITLE
Waiting until deposit: ETH balance check error: 1000000000000000000

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.core#85]
когда доходит до шага когда я должен опубликовать секрет (withdraw сделать на контракте эфира) кор не хочет этого дела потому что считает что там нет денег http://joxi.ru/Vm69NR7FDXpkar

но деньги 100% есть https://rinkeby.etherscan.io/tx/0x8a7f1f62fb21d3d3b690c08fad35d0e624aa3c4e02adea31988158a07bf285b1

**Comment by caffeinum** [comment]
нашли баг
нужно перезалить билд

**Comment by nikdementev** [comment]
это fix
